### ISSUE TITLE
Object reference not set error when retrieving IMAP data.

### ISSUE THREAD

**Issue by rkarina94** [pmengal/MailSystem.NET#33]
Hi, 

I'm using the MailSystem.Net library for a Bounced Email tracking system that I'm working on.
Firstly, I initiate an IMAP connection to GMAIL servers with ConnectSsl() using port 993.

It runs well but after a few hours, this error occurs:

"Error:Object reference not set to an instance of an object., Stack Trace:    at ActiveUp.Net.Mail.Imap4Client.Command(String command, String stamp, CommandOptions options)
   at ActiveUp.Net.Mail.Imap4Client.Command(String command, CommandOptions options)
   at ActiveUp.Net.Mail.Imap4Client.GetMailboxes(String reference, String mailboxName)
   at ActiveUp.Net.Mail.Imap4Client.SelectMailbox(String mailboxName)"

when I try to retrieve the email data from the GMAIL mail servers with this method -
 m_imapClient.SelectMailbox("NAMEOFFOLDER"). Any help would be great, thanks.

Regards,
 
Adhy

**Comment by reinaldocoelho** [comment]
Hi @rkarina94 !

Can you share the code or an example of code who cause error?

Thank you.
